### ISSUE TITLE
Error: Bad Request 

### ISSUE THREAD

**Issue by DasCalamity** [MaxGfeller/youtube-search#29]
Error: Bad Request
    at Request._callback (C:\Users\James\node_modules\youtube-search\index.js:65:21)
    at Request.self.callback (C:\Users\James\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\James\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\James\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)

**Comment by frankhale** [comment]
It would be really helpful if you posted a small example that demonstrates this issue
