### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by chuchuva** [MaxGfeller/youtube-search#39]
Searching for `Minecraft` results in this error:
> TypeError: Cannot read property 'kind' of undefined

Call stack:
````
1    at /myapp/node_modules/youtube-search/index.js:79:25
        switch (item.id.kind) {

2    at Array.map (<anonymous>)

3    at Request._callback (/home/pasha/kids-api.safe.vision/node_modules/youtube-search/index.js:76:35)
        var findings = result.items.map(function (item) {

4    at Request.self.callback (/myapp/node_modules/request/request.js:186:22)
        self._callback.apply(self, arguments)
````

**Comment by MaxGfeller** [comment]
Could you please provide a code sample with which this can be reproduced?

**Comment by chuchuva** [comment]
It is back to normal now. Must been a problem with YouTube API itself. Sorry for troubling you.
