### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by FireController1847** [MaxGfeller/youtube-search#44]
Not sure what's going on. My Google API token is valid.

**Reproduceable Code**
```js
  async getVideoURL(query) {
    let url = yt.getVideoID(query);
    if (url instanceof Error) {
      const res = await yts(query, {
        maxResults: 1,
        key: gapitoken,
        type: "video"
      });
      if (res.length <= 0) return null;
      url = res[0].link;
    }
    return url;
  }
```
(This is a method in a class, so there's not function keyword).

**Full Error**
```js
Error: Bad Request
    at Request._callback (C:\Users\Owner\Desktop\Development\Git\_CAT Discord Bots\fm-radio\node_modules\youtube-search\index.js:76:21)
    at Request.self.callback (C:\Users\Owner\Desktop\Development\Git\_CAT Discord Bots\fm-radio\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\Owner\Desktop\Development\Git\_CAT Discord Bots\fm-radio\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\Owner\Desktop\Development\Git\_CAT Discord Bots\fm-radio\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by FireController1847** [comment]
I'm using v1.1.1 and I will say directly calling the API via Postman works fine. It's an issue with this module only.

**Comment by MaxGfeller** [comment]
What does the `query` look like in this example?

**Comment by FireController1847** [comment]
`query` can be any string. In my case I'm searching music so I've been testing with the string "little too close"

**Comment by MaxGfeller** [comment]
I tried it with the exact same arguments you gave and it worked:

```javascript
var results = await search('little too close', {
  maxResults: 1,
  key: key,
  type: 'video'
})
console.log(results.results)

/*
 [ { id: 'CQFGAmiWQmg',
    link: 'https://www.youtube.com/watch?v=CQFGAmiWQmg',
    kind: 'youtube#video',
    publishedAt: '2015-08-24T18:55:12.000Z',
    channelId: 'UCJ6td3C9QlPO9O_J5dF4ZzA',
    channelTitle: 'Monstercat: Uncaged',
    title: '[Indie Dance] - WRLD - Little Too Close (feat. Veronika Redd) [Monstercat EP Release]',
    description: 'Support on iTunes: http://monster.cat/1Gx7Nqr Support on Beatport: http://monster.cat/1EedS0K Support on Bandcamp: http://monster.cat/1JnsEPb --- Listen on ...',
    thumbnails: { default: [Object], medium: [Object], high: [Object] } } ]
*/
```

Are you sure your API key is valid? Can you maybe check what exact request you're sending?

**Comment by FireController1847** [comment]
I checked my API key and when I run the function it doesn't say that a request was made... Do I need to make a new app with a new API key?

**Comment by FireController1847** [comment]
Oh, odd. Very interesting. The results aren't coming back in an Array anymore, they're coming back in an object called "results". Here's an example:
```js
/*
{ results:
   [ { id: 'CQFGAmiWQmg',
       link: 'https://www.youtube.com/watch?v=CQFGAmiWQmg',
       kind: 'youtube#video',
       publishedAt: '2015-08-24T18:55:12.000Z',
       channelId: 'UCJ6td3C9QlPO9O_J5dF4ZzA',
       channelTitle: 'Monstercat: Uncaged',
       title: '[Indie Dance] - WRLD - Little Too Close (feat. Veronika Redd) [Monstercat EP Release]',
       description: 'Support on iTunes: http://monster.cat/1Gx7Nqr Support on Beatport: http://monster.cat/1EedS0K Support on Bandcamp: http://monster.cat/1JnsEPb --- Listen on ...',
       thumbnails: [Object] } ],
  pageInfo:
   { totalResults: 1000000,
     resultsPerPage: 1,
     nextPageToken: 'CAEQAA',
     prevPageToken: undefined }
*/
```

**Comment by MaxGfeller** [comment]
Yep, this is the return value for the Promise (because we can only return one value). It still doesn't explain the "Bad Request" error though, does it? 🤔

**Comment by FireController1847** [comment]
Hmm, I guess not, but it's working now lol
