### ISSUE TITLE
Can't search with the package

### ISSUE THREAD

**Issue by JustAPieOP** [MaxGfeller/youtube-search#62]
Hi, i have tried to search with the package but it returned status 403, i am sure that my key is accessible and it is valid

**Comment by michaelCaleyWhaley** [comment]
I have just tried to search after inputting my api key, also getting a 403

**Comment by subiabre** [comment]
Exact same problem here.

```bash
Request failed with status code 403
    Error: Request failed with status code 403
        at createError (/home/subiabre/Code/castor/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/home/subiabre/Code/castor/node_modules/axios/lib/core/settle.js:18:12)
        at IncomingMessage.handleStreamEnd (/home/subiabre/Code/castor/node_modules/axios/lib/adapters/http.js:202:11)
        at IncomingMessage.emit (events.js:327:22)
        at endReadableNT (_stream_readable.js:1220:12)
        at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
 It was working perfectly fine but then it didn't.

**Comment by ZyorYT** [comment]
same

**Comment by MaxGfeller** [comment]
Can y'all check if your keys are really valid?

https://github.com/MaxGfeller/youtube-search/issues/60#issuecomment-630935747

**Comment by ZyorYT** [comment]
Im on windows, and cant run that curl.
It just gives some response about not finding the file on file system

**Comment by MaxGfeller** [comment]
You can try it in your browser, too: 

https://www.googleapis.com/youtube/v3/search\?key\=<your_key>\&part\=snippet
